version: "3.9"

services:
  marketplace_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}
        VITE_FRONTEND_URL: ${VITE_FRONTEND_URL:-http://localhost:5174}
    container_name: marketplace_frontend
    restart: unless-stopped
    ports:
      - "${FRONT_PORT:-5174}:80"
    env_file:
      - .env
    networks:
      - marketplace_net

networks:
  marketplace_net:
    external: true
